name: Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

env:
  COVER_REPORT_PATH: ./coverage/clover.xml
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '17']
    name: Test on node version ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: yarn install
      - name: Lint commit
        run:
          yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to
          ${{ github.event.pull_request.head.sha }} --verbose
      - name: Lint js
        run: yarn lint
      - name: Tests
        run: yarn test-all
  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: yarn install
      - name: Test with coverage
        run: c8 --reporter=clover yarn test-all
      - name: Send coverage info to codecoverage
        uses: codecov/codecov-action@v2
        with:
          file: ${{ env.COVER_REPORT_PATH }}
