# ==============================================================================
# Coverage Information
# ==============================================================================
# Execute coverage command and upload to codecov.
# This allows us to display a badge in the readme.md
#
# This happens every time changes are pushed to the main branch
# ==============================================================================
name: Coverage

on:
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Send to Codecov
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - run: yarn install
      - name: Test with coverage
        run: yarn c8 --reporter=lcovonly yarn test-all
      - name: Send coverage info to codecoverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage/lcov.info
