name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' }}
    name: Test on node version ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '17']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - name: Lint commits
        run:
          yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to
          ${{ github.event.pull_request.head.sha }} --verbose
      - name: Lint js
        run: yarn lint
      - name: Tests with coverage
        run: yarn ci:coverage
