# ==============================================================================
# Pull Request Checks
# ==============================================================================
# Makes sure that on different version of node:
# - all tests pass
# - coverage is 100%
# - commits are valid (conventional-commits)
# ==============================================================================
name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  build:
    name: Test on node version ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '19']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - name: Lint js
        run: yarn lint
      - name: Tests with coverage
        run: yarn ci:coverage
