# ==============================================================================
# Changeset + Release NPM Package
# ==============================================================================
# We are using changeset to manage release packages and changelogs
# Every time a PR is merged to main the action will check if there is a
# changeset and create/update a release branch and create a pull request
# for that branch.
# When that release PR is merged to main changeset will publish the package to
# npm by executing `yarn release`
#
# Note: auto commit messages from changeset will contain a [skip-ci] description
# which will stop PR merges back to main to trigger this action.
#
# For this reason the `commit` option in `./changeset/config.json` was set
# to `false`
# ==============================================================================
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: 'chore(release): changesets versioning & publication'
          title: 'Changesets: Versioning & Publication'
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
