# ==============================================================================
# Changeset + Release NPM Package
# ==============================================================================
# We are using changeset to manage release packages and changelogs
#
# Every time a PR is merged to main, the action will check if there is a
# changeset and create/update a release branch and create a pull request
# for that branch.
#
# When that release PR is merged to main changeset will publish the package to
# npm by executing `yarn release`
# ==============================================================================
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn

      - run: yarn build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: 'chore(release): changesets versioning & publication'
          title: 'Changesets: Versioning & Publication'
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
